### ISSUE TITLE
No such file or directory 'rustc`

### ISSUE THREAD

**Issue by tcco** [nayaverdier/instater#1]
My condition for rust is unable to complete 

Task
```
- name: Install rust
  command:
    command: brew install rustup  && rustup-init
    condition: rustc --version
    condition_code: 1
```

Output (attached)
<img width="716" alt="Screen Shot 2021-12-25 at 10 57 01 AM" src="https://user-images.githubusercontent.com/6300445/147391759-5b17424a-92ad-448c-bdbf-a893b6ff31f5.png">
